---
- hosts: all
  gather_facts: True

  vars:
    nodejs_version: "7"
    debian_repo_version: "7.x"
    site_name: playground.machinomy.com
    site_dir: "/srv/www/{{site_name}}"

  tasks:

    - name: Ensure the system can use the HTTPS transport for APT
      stat:
        path: /usr/lib/apt/methods/https
      register: apt_https_transport

    - name: Install HTTPS transport for APT
      apt:
        pkg: apt-transport-https
        state: installed
      when: not apt_https_transport.stat.exists

    - name: Import the NodeSource GPG key into apt
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present
      become: yes
      become_user: root

    - name: Add NodeSource deb repository
      apt_repository:
        repo: 'deb https://deb.nodesource.com/node_{{ debian_repo_version }} {{ ansible_distribution_release }} main'
        state: present
      become: yes
      become_user: root

    - name: Add NodeSource deb-src repository
      apt_repository:
        repo: 'deb-src https://deb.nodesource.com/node_{{ debian_repo_version }} {{ ansible_distribution_release }} main'
        state: present
      become: yes
      become_user: root

    - name: Install Node.js
      apt:
        pkg:
          - nodejs={{ nodejs_version }}*
        state: installed
        update_cache: yes
      become: yes
      become_user: root

    - name: Make /srv/www/playground.machinomy.com folder
      file:
        path: "{{site_dir}}"
        recurse: yes
        state: directory
        owner: "{{ansible_user_id}}"
      become: yes
      become_user: root

    - name: Git
      git:
        repo: git@github.com:machinomy/playground.machinomy.com.git
        dest: "{{site_dir}}"
        accept_hostkey: yes

    - name: Install npm dependencies
      command: npm install
      args:
        chdir: "{{site_dir}}"

    - name: Install pm2
      command: npm install -g pm2
      args:
        chdir: "{{site_dir}}"


